nodeLinker: pnp

enableHardenedMode: false

supportedArchitectures:
  os:
    - linux
    - win32
    - darwin

npmAuditIgnoreAdvisories:
  - 1097346 # ip vuln, unlikely to affect us (or be fixed very quickly)

logFilters:
  # fail on missing peer dependency
  - code: YN0002
    level: error
  # fail on wrong version of dependency
  - code: YN0060
    level: error
